spring.application.name=FoodSave

server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/foodsave_test
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=E5tH1ttofclaLK4KjVG3Q54n3tgOjAhaSfk1IzXwlAH
jwt.expiration=86400000
