import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { ArrowRight, BadgeCheck, Building2, Camera, CheckCircle2, Clock3, Copy, CreditCard, Leaf, LocateFixed, LogOut, MapPin, PackageCheck, Pencil, Plus, QrCode, RefreshCw, ScanLine, ShieldCheck, ShoppingBag, Star, Ticket, Trash2, UserRound, X } from "lucide-react";
import { api } from "./api";
import type { BusinessProfile, FoodSaveQrResponse, Impact, Listing, Order, Profile, Review } from "./types";

type Modal = "profile"|"password"|"listing"|"business"|"order"|"qr"|"review"|"scanner"|"impact"|null;
type Toast = {type:"success"|"error";text:string}|null;
const money=(v:number)=>new Intl.NumberFormat("ru-RU").format(v)+" ₸";
const dt=(v:string)=>new Date(v).toLocaleString("ru-RU",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"});
const time=(v:string)=>new Date(v).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"});
const disc=(a:number,b:number)=>a?Math.max(0,Math.round((1-b/a)*100)):0;
const qrImg=(data:string)=>`https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(data)}`;
const errText=(e:unknown,f:string)=>e instanceof Error?e.message:f;

export default function App(){
 const [profile,setProfile]=useState<Profile|null>(null); const [listings,setListings]=useState<Listing[]>([]); const [myListings,setMyListings]=useState<Listing[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [impact,setImpact]=useState<Impact|null>(null); const [reviews,setReviews]=useState<Review[]>([]); const [business,setBusiness]=useState<BusinessProfile|null>(null);
 const [modal,setModal]=useState<Modal>(null); const [selected,setSelected]=useState<Listing|null>(null); const [selectedOrder,setSelectedOrder]=useState<Order|null>(null); const [qr,setQr]=useState<FoodSaveQrResponse|null>(null); const [toast,setToast]=useState<Toast>(null); const [loading,setLoading]=useState(false); const [auth,setAuth]=useState<"login"|"register">("login"); const [authOpen,setAuthOpen]=useState(false); const [nearby,setNearby]=useState(false); const [coords,setCoords]=useState<{lat:number;lon:number}|null>(null);
 const logged=Boolean(localStorage.getItem("foodsave_token")); const isBusiness=profile?.role==="BUSINESS";
 const stats=useMemo(()=>({saved:orders.filter(o=>o.status==="COMPLETED").reduce((s,o)=>s+o.quantity,0),spent:orders.reduce((s,o)=>s+o.totalPrice,0)}),[orders]);
 useEffect(()=>{if(logged) refresh();},[]); useEffect(()=>{if(!toast)return;const x=setTimeout(()=>setToast(null),3500);return()=>clearTimeout(x)},[toast]);
 async function refresh(){setLoading(true);try{const [p,l,o]=await Promise.all([api.getProfile(),api.getListings(),api.getMyOrders()]);setProfile(p);setListings(l);setOrders(o);if(p.role==="BUSINESS"){const [b,ml]=await Promise.all([api.getBusinessProfile().catch(()=>null),api.getMyListings().catch(()=>[])]);setBusiness(b);setMyListings(ml)}}catch(e){setToast({type:"error",text:errText(e,"Не удалось загрузить данные")})}finally{setLoading(false)}}
 async function login(email:string,password:string){setLoading(true);try{const r=await api.login({email,password});localStorage.setItem("foodsave_token",r.token);setAuthOpen(false);setToast({type:"success",text:"Добро пожаловать в FoodSave"});await refresh()}catch(e){setToast({type:"error",text:errText(e,"Ошибка входа")})}finally{setLoading(false)}}
 async function register(data:{username:string;email:string;phoneNumber:string;password:string;city:string}){setLoading(true);try{const r=await api.register(data);localStorage.setItem("foodsave_token",r.token);setAuthOpen(false);setToast({type:"success",text:"Аккаунт создан"});await refresh()}catch(e){setToast({type:"error",text:errText(e,"Ошибка регистрации")})}finally{setLoading(false)}}
 function logout(){localStorage.removeItem("foodsave_token");setProfile(null);setOrders([]);setListings([]);setBusiness(null)}
 async function locate(){navigator.geolocation.getCurrentPosition(async p=>{const c={lat:p.coords.latitude,lon:p.coords.longitude};setCoords(c);setNearby(true);try{setListings(await api.getNearbyListings(c.lat,c.lon,10))}catch(e){setToast({type:"error",text:errText(e,"Не удалось получить предложения рядом")})}},()=>setToast({type:"error",text:"Разреши геолокацию в браузере"}))}
 async function createOrder(l:Listing,q:number){try{const o=await api.createOrder(l.id,q);setSelected(null);await refresh();setSelectedOrder(o);setModal("order");setToast({type:"success",text:"Заказ создан. Теперь его можно оплатить"})}catch(e){setToast({type:"error",text:errText(e,"Не удалось создать заказ")})}}
 async function pay(o:Order){try{await api.payForOrder(o.id);const q=await api.getOrderQr(o.id);setQr(q);setSelectedOrder(o);setModal("qr");await refresh();setToast({type:"success",text:"Оплата успешна. Покажи QR бизнесу при получении"})}catch(e){setToast({type:"error",text:errText(e,"Не удалось оплатить заказ")})}}
 async function loadImpact(){try{setImpact(await api.getImpact());setModal("impact")}catch(e){setToast({type:"error",text:errText(e,"Не удалось загрузить статистику")})}}
 async function review(order:Order,rating:number,comment:string){try{await api.createReview({orderId:order.id,rating,comment});setModal(null);setToast({type:"success",text:"Спасибо за отзыв"})}catch(e){setToast({type:"error",text:errText(e,"Не удалось оставить отзыв")})}}
 if(!logged||!profile)return <><Landing onAuth={m=>{setAuth(m);setAuthOpen(true)}}/>{authOpen&&<AuthModal mode={auth} loading={loading} onClose={()=>setAuthOpen(false)} onMode={setAuth} onLogin={login} onRegister={register}/>} {toast&&<Toast t={toast}/>}</>;
 return <div className="app-shell"><header className="topbar"><div className="container nav"><div className="brand" onClick={()=>scrollTo({top:0,behavior:"smooth"})}><span className="brand-mark"><Leaf size={18}/></span>Food<span>Save</span></div><nav><a href="#discover">Предложения</a><a href="#orders">Заказы</a><a href="#impact">Мой вклад</a>{isBusiness&&<a href="#business">Business</a>}</nav><div className="actions"><button className="icon-btn" onClick={refresh}><RefreshCw size={17} className={loading?"spin":""}/></button>{isBusiness&&<button className="icon-btn" title="Сканировать QR" onClick={()=>setModal("scanner")}><ScanLine size={18}/></button>}<button className="profile-chip" onClick={()=>setModal("profile")}><span className="avatar">{profile.username[0].toUpperCase()}</span><b>{profile.username}</b></button><button className="icon-btn" onClick={logout}><LogOut size={17}/></button></div></div></header>
 <main><section className="hero container"><div><span className="eyebrow"><SparkIcon/> Спасаем еду вместе</span><h1>Хорошая еда.<br/><em>Не пропадёт.</em></h1><p>Находи еду со скидкой до 90%, бронируй и забирай рядом с собой.</p><div className="hero-actions"><a className="primary-btn" href="#discover">Найти еду <ArrowRight size={17}/></a><button className="ghost-btn" onClick={locate}><LocateFixed size={17}/> Рядом со мной</button></div></div><div className="hero-art"><div className="hero-orb"/><div className="hero-food">🥐</div><div className="floating f1"><Leaf size={16}/><b>−90%</b><small>скидка</small></div><div className="floating f2"><MapPin size={16}/><b>{nearby?"до 10 км":"Алматы"}</b><small>{nearby?"рядом":"FoodSave"}</small></div></div></section>
 <section className="impact-strip"><div className="container stat-grid"><Stat v={`${stats.saved}`} l="товаров спасено"/><Stat v={money(stats.spent)} l="потрачено"/><Stat v={`${listings.length}`} l="предложений"/><Stat v={impact?`${impact.foodSavedKg} кг`:`${profile.foodPoints??0}`} l={impact?"еды спасено":"FoodPoints"}/></div></section>
 <section id="discover" className="section container"><div className="heading"><div><span className="kicker">{nearby?"Рядом с тобой":"Все предложения"}</span><h2>Спасти сегодня</h2></div><div className="heading-actions"><button className="ghost-btn small" onClick={nearby?async()=>{setNearby(false);setListings(await api.getListings())}:locate}><MapPin size={15}/>{nearby?"Показать все":"Найти рядом"}</button></div></div>{nearby&&coords&&<div className="map-panel"><div className="map-grid">{listings.slice(0,8).map((l,i)=><div key={l.id} className="map-pin" style={{left:`${15+(i*17)%75}%`,top:`${25+(i*23)%55}%`}} title={l.businessName}><MapPin size={25}/></div>)}<div className="map-user"><LocateFixed size={17}/></div></div><div className="map-info"><b>Предложения в радиусе 10 км</b><span>Геолокация: {coords.lat.toFixed(4)}, {coords.lon.toFixed(4)}</span><small>Карта использует координаты BusinessProfile из backend.</small></div></div>}{listings.length?<div className="listing-grid">{listings.map(l=><ListingCard key={l.id} listing={l} onOpen={()=>{setSelected(l);setModal("order")}}/>)}</div>:<Empty business={isBusiness} onCreate={()=>setModal("listing")}/>}</section>
 <section id="orders" className="section soft"><div className="container"><div className="heading"><div><span className="kicker">История</span><h2>Мои заказы</h2></div><span className="count">{orders.length}</span></div>{orders.length?<div className="orders">{orders.map(o=><OrderRow key={o.id} order={o} onPay={()=>pay(o)} onQr={async()=>{try{setQr(await api.getOrderQr(o.id));setSelectedOrder(o);setModal("qr")}catch(e){setToast({type:"error",text:errText(e,"QR пока недоступен")})}}} onReview={()=>{setSelectedOrder(o);setModal("review")}} onCancel={async()=>{try{await api.cancelOrder(o.id);await refresh()}catch(e){setToast({type:"error",text:errText(e,"Не удалось отменить заказ")})}}}/>)}</div>:<Empty/>}</div></section>
 <section id="impact" className="section container"><div className="impact-card"><div><span className="kicker">Твой вклад</span><h2>Каждая покупка имеет эффект.</h2><p>FoodSave показывает накопленные результаты только по завершённым заказам.</p></div><button className="primary-btn" onClick={loadImpact}><Leaf size={17}/> Открыть статистику</button></div></section>
 {isBusiness&&<section id="business" className="section container business"><div className="business-head"><div><span className="kicker">FoodSave Business</span><h2>{business?.businessName||"Настрой бизнес-профиль"}</h2><p>{business?.address||"Добавь адрес, чтобы предложения получили координаты и появились рядом на карте."}</p></div><div className="business-actions">{!business&&<button className="primary-btn" onClick={()=>setModal("business")}><Building2 size={17}/> Создать профиль</button>}<button className="ghost-btn" onClick={()=>setModal("scanner")}><ScanLine size={17}/> Сканировать QR</button>{business&&<button className="ghost-btn" onClick={()=>setModal("business")}><Pencil size={16}/> Изменить</button>}</div></div><div className="business-grid"><div><h3>Мои предложения</h3>{myListings.length?myListings.map(l=><div className="my-listing" key={l.id}><div><b>{l.title}</b><span>{money(l.foodSavePrice)} · ×{l.quantity}</span></div><button className="danger-icon" onClick={async()=>{try{await api.cancelListing(l.id);await refresh()}catch(e){setToast({type:"error",text:errText(e,"Не удалось отменить")})}}}><Trash2 size={16}/></button></div>):<p className="muted">Пока нет объявлений.</p>}<button className="primary-btn" onClick={()=>setModal("listing")}><Plus size={17}/> Новое предложение</button></div><div className="business-rating"><Star size={24}/><b>{(awaitableRating(profile))}</b><span>Рейтинг бизнеса можно получать из /reviews/my/rating</span></div></div></section>}
 </main><footer><div className="container footer"><b>Food<span>Save</span></b><span>Спасение еды — спасение планеты.</span><span>© 2026</span></div></footer>
 {modal==="profile"&&<ProfileModal profile={profile} onClose={()=>setModal(null)} onSaved={p=>{setProfile(p);setModal(null)}} onPassword={()=>setModal("password")} onQr={async()=>{try{setQr(await api.getQr());setModal("qr") }catch(e){setToast({type:"error",text:errText(e,"QR недоступен")})}}}/>} {modal==="password"&&<PasswordModal close={()=>setModal("profile")} toast={setToast}/>} {modal==="listing"&&<ListingModal close={()=>setModal(null)} submit={async d=>{try{await api.createListing(d);setModal(null);await refresh();setToast({type:"success",text:"Предложение опубликовано"})}catch(e){setToast({type:"error",text:errText(e,"Не удалось создать предложение")})}}}/>} {modal==="order"&&selected&&<OrderModal listing={selected} close={()=>setModal(null)} submit={createOrder}/>} {modal==="qr"&&qr&&<QrModal qr={qr.qrData} close={()=>setModal(null)}/>} {modal==="review"&&selectedOrder&&<ReviewModal order={selectedOrder} close={()=>setModal(null)} submit={review}/>} {modal==="impact"&&impact&&<ImpactModal data={impact} close={()=>setModal(null)}/>} {modal==="business"&&<BusinessModal business={business} close={()=>setModal(null)} save={async d=>{try{const b=business?await api.updateBusinessProfile(d):await api.createBusinessProfile(d);setBusiness(b);setModal(null);await refresh();setToast({type:"success",text:"Бизнес-профиль сохранён"})}catch(e){setToast({type:"error",text:errText(e,"Не удалось сохранить профиль")})}}}/>} {modal==="scanner"&&<ScannerModal close={()=>setModal(null)} scan={async token=>{try{await api.scanOrderQr(token);setModal(null);await refresh();setToast({type:"success",text:"Заказ подтверждён. Клиент получил FoodPoints."})}catch(e){setToast({type:"error",text:errText(e,"QR не принят")})}}}/>} {toast&&<Toast t={toast}/>}</div>
}
function awaitableRating(p:Profile){return p.role==="BUSINESS"?"—":""}
function SparkIcon(){return <span className="spark">✦</span>}
function Stat({v,l}:{v:string;l:string}){return <div className="stat"><b>{v}</b><span>{l}</span></div>}
function Empty({business,onCreate}:{business?:boolean;onCreate?:()=>void}){return <div className="empty"><ShoppingBag size={28}/><h3>Пока пусто</h3><p>Когда появится предложение, оно будет здесь.</p>{business&&onCreate&&<button className="primary-btn" onClick={onCreate}><Plus size={17}/> Создать предложение</button>}</div>}
function ListingCard({listing:l,onOpen}:{listing:Listing;onOpen:()=>void}){return <article className="listing-card"><div className="listing-image"><span className="food-emoji">{foodEmoji(l.title)}</span><b className="discount">−{disc(l.originalPrice,l.foodSavePrice)}%</b><span className="available">● {l.status==="ACTIVE"?"Доступно":l.status}</span></div><div className="listing-body"><div className="title-line"><h3>{l.title}</h3><span>×{l.quantity}</span></div><p>{l.description||"Предложение от FoodSave Business"}</p><div className="meta"><span><Building2 size={13}/> {l.businessName||"Бизнес"}</span>{l.businessRating!=null&&<span><Star size={13}/> {l.businessRating.toFixed(1)}</span>}{l.distanceKm!=null&&<span><MapPin size={13}/> {l.distanceKm.toFixed(1)} км</span>}</div><div className="pickup"><Clock3 size={14}/> {dt(l.pickupStart)} — {time(l.pickupEnd)}</div><div className="price"><div><del>{money(l.originalPrice)}</del><b>{money(l.foodSavePrice)}</b></div><button className="circle" onClick={onOpen}><ArrowRight size={18}/></button></div></div></article>}
function foodEmoji(t:string){const x=t.toLowerCase();if(x.includes("пиц"))return"🍕";if(x.includes("суш"))return"🍣";if(x.includes("бургер"))return"🍔";if(x.includes("коф"))return"☕";if(x.includes("салат"))return"🥗";if(x.includes("хлеб")||x.includes("выпеч"))return"🥐";return"🥡"}
function OrderRow({order:o,onPay,onQr,onReview,onCancel}:{order:Order;onPay:()=>void;onQr:()=>void;onReview:()=>void;onCancel:()=>void}){const label:{[k:string]:string}={RESERVED:"Зарезервирован",COMPLETED:"Завершён",CANCELLED:"Отменён",EXPIRED:"Истёк",NO_SHOW:"Не забран"};return <div className="order-row"><div className="order-icon"><PackageCheck size={20}/></div><div className="order-main"><b>{o.listingTitle}</b><span>{o.quantity} шт. · {dt(o.createdAt)}</span><small><Clock3 size={12}/> {time(o.pickupStart)} — {time(o.pickupEnd)}</small></div><div className="order-right"><b>{money(o.totalPrice)}</b><span className={`status status-${o.status.toLowerCase()}`}>{label[o.status]}</span><div className="row-actions">{o.status==="RESERVED"&&<><button onClick={onPay}><CreditCard size={14}/> Оплатить</button><button onClick={onQr}><QrCode size={14}/> QR</button><button onClick={onCancel}>Отмена</button></>}{o.status==="COMPLETED"&&<button onClick={onReview}><Star size={14}/> Отзыв</button>}</div></div></div>}
function Modal({children,close,wide=false}:{children:ReactNode;close:()=>void;wide?:boolean}){return <div className="backdrop"><div className={`modal ${wide?"wide":""}`}><button className="close" onClick={close}><X size={18}/></button>{children}</div></div>}
function Field({label,value,onChange,type="text",placeholder,required=true}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string;required?:boolean}){return <label className="field"><span>{label}</span><input type={type} value={value} placeholder={placeholder} required={required} onChange={e=>onChange(e.target.value)}/></label>}
function AuthModal({mode,loading,onClose,onMode,onLogin,onRegister}:{mode:"login"|"register";loading:boolean;onClose:()=>void;onMode:(m:"login"|"register")=>void;onLogin:(e:string,p:string)=>void;onRegister:(d:{username:string;email:string;phoneNumber:string;password:string;city:string})=>void}){const [f,setF]=useState({username:"",email:"",phoneNumber:"",password:"",city:"Almaty"});return <Modal close={onClose}><div className="auth-head"><div className="modal-icon"><Leaf size={22}/></div><span className="kicker">FoodSave</span><h2>{mode==="login"?"С возвращением":"Создать аккаунт"}</h2></div><form className="form-stack" onSubmit={e=>{e.preventDefault();mode==="login"?onLogin(f.email,f.password):onRegister(f)}}>{mode==="register"&&<Field label="Имя" value={f.username} onChange={v=>setF({...f,username:v})}/>}<Field label="Email" type="email" value={f.email} onChange={v=>setF({...f,email:v})}/>{mode==="register"&&<Field label="Телефон" value={f.phoneNumber} onChange={v=>setF({...f,phoneNumber:v})}/>}<Field label="Пароль" type="password" value={f.password} onChange={v=>setF({...f,password:v})}/>{mode==="register"&&<Field label="Город" value={f.city} onChange={v=>setF({...f,city:v})}/>}<button className="primary-btn full" disabled={loading}>{loading?"Подождите…":mode==="login"?"Войти":"Зарегистрироваться"}<ArrowRight size={17}/></button></form><div className="switch">{mode==="login"?"Нет аккаунта?":"Уже зарегистрирован?"}<button onClick={()=>onMode(mode==="login"?"register":"login")}>{mode==="login"?"Создать":"Войти"}</button></div></Modal>}
function ProfileModal({profile:p,onClose,onSaved,onPassword,onQr}:{profile:Profile;onClose:()=>void;onSaved:(p:Profile)=>void;onPassword:()=>void;onQr:()=>void}){const [email,setEmail]=useState(p.email),[phone,setPhone]=useState(p.phoneNumber),[city,setCity]=useState(p.city);return <Modal close={onClose}><div className="profile-top"><div className="avatar-big">{p.username[0].toUpperCase()}</div><div><span className="kicker">Мой профиль</span><h2>{p.username}</h2><span className="role">{p.role}</span></div></div><div className="profile-stats"><b>{p.foodPoints??0}<small>FoodPoints</small></b><b>{p.reliability??100}%<small>Надёжность</small></b><b>{p.completedOrders??0}<small>Завершено</small></b></div><div className="fsid"><div><Ticket size={18}/><span><small>FoodSave ID</small><b>{p.fsId}</b></span></div><button onClick={()=>navigator.clipboard?.writeText(p.fsId)}><Copy size={16}/></button></div><div className="profile-buttons"><button className="ghost-btn full" onClick={onQr}><QrCode size={16}/> Мой QR</button><button className="ghost-btn full" onClick={onPassword}><ShieldCheck size={16}/> Пароль</button></div><form className="form-stack" onSubmit={async e=>{e.preventDefault();try{onSaved(await api.updateProfile({email,phoneNumber:phone,city}))}catch{}}}><Field label="Email" type="email" value={email} onChange={setEmail}/><Field label="Телефон" value={phone} onChange={setPhone}/><Field label="Город" value={city} onChange={setCity}/><div className="locked"><UserRound size={16}/> Username: <b>{p.username}</b><span>не изменяется</span></div><button className="primary-btn full">Сохранить изменения</button></form></Modal>}
function PasswordModal({close,toast}:{close:()=>void;toast:(t:Toast)=>void}){const [a,setA]=useState(""),[b,setB]=useState("");return <Modal close={close}><span className="kicker">Безопасность</span><h2>Сменить пароль</h2><form className="form-stack" onSubmit={async e=>{e.preventDefault();try{await api.changePassword({oldPassword:a,newPassword:b});toast({type:"success",text:"Пароль изменён"});close()}catch(x){toast({type:"error",text:errText(x,"Ошибка")})}}}><Field label="Старый пароль" type="password" value={a} onChange={setA}/><Field label="Новый пароль" type="password" value={b} onChange={setB}/><button className="primary-btn full">Изменить</button></form></Modal>}
function ListingModal({close,submit}:{close:()=>void;submit:(d:any)=>void}){const d=new Date(),e=new Date(Date.now()+3*3600000),local=(x:Date)=>{const p=(n:number)=>String(n).padStart(2,"0");return`${x.getFullYear()}-${p(x.getMonth()+1)}-${p(x.getDate())}T${p(x.getHours())}:${p(x.getMinutes())}`};const [f,setF]=useState({title:"Пицца Маргарита",description:"Свежая пицца со скидкой",originalPrice:"3500",foodSavePrice:"1500",quantity:"5",weightKg:"0.45",pickupStart:local(d),pickupEnd:local(e),expiresAt:local(e)});const set=(k:string,v:string)=>setF({...f,[k]:v});return <Modal close={close} wide><span className="kicker">Business</span><h2>Новое предложение</h2><form className="form-grid" onSubmit={e=>{e.preventDefault();submit({...f,originalPrice:+f.originalPrice,foodSavePrice:+f.foodSavePrice,quantity:+f.quantity,weightKg:+f.weightKg})}}><div className="span"><Field label="Название" value={f.title} onChange={v=>set("title",v)}/></div><div className="span"><Field label="Описание" value={f.description} onChange={v=>set("description",v)} required={false}/></div><Field label="Обычная цена" type="number" value={f.originalPrice} onChange={v=>set("originalPrice",v)}/><Field label="Цена FoodSave" type="number" value={f.foodSavePrice} onChange={v=>set("foodSavePrice",v)}/><Field label="Количество" type="number" value={f.quantity} onChange={v=>set("quantity",v)}/><Field label="Вес 1 шт. (кг)" type="number" value={f.weightKg} onChange={v=>set("weightKg",v)}/><Field label="Забрать с" type="datetime-local" value={f.pickupStart} onChange={v=>set("pickupStart",v)}/><Field label="Забрать до" type="datetime-local" value={f.pickupEnd} onChange={v=>set("pickupEnd",v)}/><div className="span"><Field label="Истекает" type="datetime-local" value={f.expiresAt} onChange={v=>set("expiresAt",v)}/></div><div className="form-end span"><button type="button" className="ghost-btn" onClick={close}>Отмена</button><button className="primary-btn">Опубликовать <ArrowRight size={16}/></button></div></form></Modal>}
function OrderModal({listing:l,close,submit}:{listing:Listing;close:()=>void;submit:(l:Listing,q:number)=>void}){const [q,setQ]=useState(1);return <Modal close={close}><div className="order-preview"><span>{foodEmoji(l.title)}</span><b>−{disc(l.originalPrice,l.foodSavePrice)}%</b></div><span className="kicker">{l.businessName||"FoodSave Business"}</span><h2>{l.title}</h2><p className="muted">{l.description}</p><div className="details"><span><Clock3 size={14}/> {dt(l.pickupStart)} — {time(l.pickupEnd)}</span><span><MapPin size={14}/> {l.distanceKm!=null?`${l.distanceKm.toFixed(1)} км`:"координаты бизнеса"}</span><span><Star size={14}/> {l.businessRating?.toFixed(1)||"—"}</span></div><div className="qty"><span>Количество</span><div><button onClick={()=>setQ(Math.max(1,q-1))}>−</button><b>{q}</b><button onClick={()=>setQ(Math.min(l.quantity,q+1))}>+</button></div></div><div className="checkout"><div><small>Итого</small><b>{money(l.foodSavePrice*q)}</b></div><button className="primary-btn" onClick={()=>submit(l,q)}>Забронировать <ArrowRight size={16}/></button></div><div className="note">После бронирования заказ можно оплатить прямо в разделе «Мои заказы». Оплата здесь тестовая, без Kaspi/банка.</div></Modal>}
function QrModal({qr,close}:{qr:string;close:()=>void}){return <Modal close={close}><div className="qr-modal"><span className="kicker">FoodSave QR</span><h2>Покажи этот QR бизнесу</h2><p>Бизнес сканирует код при выдаче. После успешного сканирования заказ станет COMPLETED.</p><div className="qr-box"><img src={qrImg(qr)} alt="Order QR"/></div><code>{qr}</code><button className="ghost-btn full" onClick={()=>navigator.clipboard?.writeText(qr)}><Copy size={15}/> Скопировать QR data</button></div></Modal>}
function ReviewModal({order:o,close,submit}:{order:Order;close:()=>void;submit:(o:Order,r:number,c:string)=>void}){const [r,setR]=useState(5),[c,setC]=useState("");return <Modal close={close}><span className="kicker">Отзыв</span><h2>{o.listingTitle}</h2><div className="stars">{[1,2,3,4,5].map(n=><button key={n} className={n<=r?"on":""} onClick={()=>setR(n)}><Star size={30} fill="currentColor"/></button>)}</div><label className="field"><span>Комментарий</span><textarea value={c} onChange={e=>setC(e.target.value)} placeholder="Как прошёл заказ?"/></label><button className="primary-btn full" onClick={()=>submit(o,r,c)}>Оставить отзыв</button></Modal>}
function ImpactModal({data:d,close}:{data:Impact;close:()=>void}){return <Modal close={close}><span className="kicker">Impact</span><h2>Твой вклад</h2><div className="impact-big"><div><b>{d.foodSavedKg}</b><span>кг еды спасено</span></div><div><b>{money(d.moneySaved)}</b><span>сэкономлено</span></div><div><b>{d.co2SavedKg}</b><span>кг CO₂e оценочно</span></div></div><p className="muted">CO₂e — расчётная оценка по коэффициенту backend, а не измерение фактических выбросов.</p></Modal>}
function BusinessModal({business:b,close,save}:{business:BusinessProfile|null;close:()=>void;save:(d:{businessName:string;description:string;address:string})=>void}){const [n,setN]=useState(b?.businessName||""),[d,setD]=useState(b?.description||""),[a,setA]=useState(b?.address||"");return <Modal close={close}><span className="kicker">Business Profile</span><h2>{b?"Изменить профиль":"Создать профиль"}</h2><p className="muted">Адрес отправляется в Nominatim и превращается в latitude/longitude для карты.</p><form className="form-stack" onSubmit={e=>{e.preventDefault();save({businessName:n,description:d,address:a})}}><Field label="Название бизнеса" value={n} onChange={setN}/><Field label="Описание" value={d} onChange={setD} required={false}/><Field label="Адрес" value={a} onChange={setA} placeholder="Алматы, ул. Абая 10"/><button className="primary-btn full">Сохранить профиль</button></form></Modal>}
function ScannerModal({close,scan}:{close:()=>void;scan:(token:string)=>void}){const [value,setValue]=useState(""),[running,setRunning]=useState(false);async function camera(){const Detector=(window as any).BarcodeDetector;if(!Detector){setRunning(false);return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}});const video=document.getElementById("qr-video") as HTMLVideoElement;video.srcObject=stream;await video.play();setRunning(true);const detector=new Detector({formats:["qr_code"]});const loop=async()=>{if(!video.videoWidth)return requestAnimationFrame(loop);const codes=await detector.detect(video);if(codes[0]?.rawValue){stream.getTracks().forEach((t:any)=>t.stop());const raw=String(codes[0].rawValue);setValue(raw);setRunning(false);scan(raw.includes("foodsave://order/")?raw.split("foodsave://order/")[1]:raw);return}requestAnimationFrame(loop)};loop()}catch{setRunning(false)}}return <Modal close={close}><span className="kicker">Business</span><h2>Сканировать заказ</h2><p className="muted">Можно использовать камеру, либо вставить QR data вручную.</p><video id="qr-video" className={running?"scanner-video":"scanner-video hidden"}/><button className="primary-btn full" onClick={camera}><Camera size={17}/> Открыть камеру</button><div className="or">или</div><Field label="QR data / token" value={value} onChange={setValue}/><button className="ghost-btn full" disabled={!value} onClick={()=>scan(value.includes("foodsave://order/")?value.split("foodsave://order/")[1]:value)}><CheckCircle2 size={16}/> Подтвердить заказ</button></Modal>}
function Toast({t}:{t:Exclude<Toast,null>}){return <div className={`toast ${t.type}`}><span/> {t.text}</div>}
function Landing({onAuth}:{onAuth:(m:"login"|"register")=>void}){return <div className="landing"><header className="topbar"><div className="container nav"><div className="brand"><span className="brand-mark"><Leaf size={18}/></span>Food<span>Save</span></div><div className="actions"><button className="ghost-btn" onClick={()=>onAuth("login")}>Войти</button><button className="primary-btn" onClick={()=>onAuth("register")}>Создать аккаунт</button></div></div></header><section className="landing-hero container"><div><span className="eyebrow"><Leaf size={15}/> Алматы · Казахстан</span><h1>Еда, которую<br/><em>успеют спасти.</em></h1><p>FoodSave соединяет людей и бизнес, чтобы хорошая еда не превращалась в отходы.</p><div className="hero-actions"><button className="primary-btn" onClick={()=>onAuth("register")}>Начать спасать <ArrowRight size={17}/></button><button className="ghost-btn" onClick={()=>onAuth("login")}>У меня уже есть аккаунт</button></div></div><div className="landing-art"><div className="landing-orb"/><div className="landing-food">🥑</div><div className="landing-card c1">−75%<small>на сегодня</small></div><div className="landing-card c2">0.8 км<small>рядом</small></div><div className="landing-card c3">до 20:00<small>забрать</small></div></div></section><section className="landing-bottom"><div className="container values"><Value icon={<Ticket/>} title="До 90% дешевле" text="Еда со скидкой, которая ещё вчера стоила дороже."/><Value icon={<MapPin/>} title="Рядом" text="Предложения можно искать по геолокации."/><Value icon={<Leaf/>} title="С пользой" text="Завершённые заказы формируют Impact Stats."/></div></section></div>}
function Value({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="value"><span>{icon}</span><div><b>{title}</b><p>{text}</p></div></div>}
